export const GET_ALL_PRODUCTS_REQUEST = "GET_ALL_PRODUCTS_REQUEST"
export const GET_ALL_PRODUCTS_RESPONSE_SUCCESS = "GET_ALL_PRODUCTS_RESPONSE_SUCCESS"
export const GET_ALL_PRODUCTS_RESPONSE_FAIL = "GET_ALL_PRODUCTS_RESPONSE_FAIL"

export const UPLOAD_PRODUCT_REQUEST = "UPLOAD_PRODUCT_REQUEST"
export const UPLOAD_PRODUCT_REQUEST_FAIL = "UPLOAD_PRODUCT_REQUEST_FAIL"
export const UPLOAD_PRODUCT_REQUEST_SUCCESS = "UPLOAD_PRODUCT_REQUEST_SUCCESS"

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST"
export const CREATE_USER_REQUEST_SUCCESS = "CREATE_USER_REQUEST_SUCCESS"
export const CREATE_USER_REQUEST_FAIL = "CREATE_USER_REQUEST_FAIL"
export const CLEAN_STATE = "CLEAN_STATE"